version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: moneytracker-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: money
      POSTGRES_DB: moneytrackerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: moneytracker-backend
    container_name: moneytracker-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: