spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneytrackerdb
    username: root
    password: money
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080
