spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneytrackerdb
    username: root
    password: money
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  graphql:
    cors:
      allowed-origins: http://localhost:3000,http://127.0.0.1:3000
      allowed-methods: POST, GET

server:
  port: 8080

